### ISSUE TITLE
Problem adding Postmark Bot to private channel

### ISSUE THREAD

**Issue by Cangit** [wildbit/pm-slack-app#6]
While /postmark commands work in any channel (public or private), I have a problem adding the Postmark Bot to a private channel- making it post on a bounce/spam complaint.

**Comment by rianvdm** [comment]
@Cangit Hmm, this should work. I just tested it again in a private channel and everything was fine. Can you let me know what error / issue you're seeing? Thanks!

**Comment by Cangit** [comment]
Ok so I figured this out and I dont think its a problem with Postmark Bot- nice to know tho.

How to reproduce:

 - Create a public channel, add postmark bot.
 - Test the webhook, everything is good 👍 
 - Make channel private
 - Postmark bot no longer works (Even though Slack insist that making the channel private should not change current app/member list)

How to get around it: Simply create the channel and make it private before adding Postmark Bot.

**Comment by rianvdm** [comment]
Ah ok, that's good to know, thanks!
